version: "3.8"

services:

  database:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - horizon-network

  backend:
    build:
      context: .
    env_file: ./.env
    depends_on:
      - database
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - horizon-network

networks:
  horizon-network:

volumes:
  mysql-data:
    driver: local
