version: "3.3"

services:

  database:
    image: mysql:5.7
    env_file: .env
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - horizon-network

  backend:
    build:
      context: .
    env_file: .env
    depends_on:
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE?useSSL=false", "spring.datasource.username" : "$MYSQL_USER", "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD", "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", "spring.jpa.hibernate.ddl-auto" : "update" }'
    networks:
      - horizon-network

networks:
  horizon-network: